package com.example.myapp

import com.example.myapp.data.Data


object MusicianObject {
    val list= listOf(
        Data(0,"Jidenna",
        sex="male",
        age=34,
            song="Bambi,Classic men,Little Bit More",
        description = "a great singer",
        puppyImageId = R.drawable.jidena),Data(0,"Kendrick",
        sex="male",
        age=30,
            song="Humble,Alright,The Blacker The Berry",
        description = "Rapper",
        puppyImageId = R.drawable.kendrick),
        Data(0,"Khalid",
            sex="male",
            age=26,
            song="Young Dumb & broke,Location,Better",
            description = "Hip Hop",
            puppyImageId = R.drawable.khalid),
        Data(0,"Khalifa",
            sex="male",
            age=39,
            song="Black and Yellow, See you Again",
            description = "Best Rapper",
            puppyImageId = R.drawable.khalifa),
        Data(0,"Pop Smoke",
            sex="male",
            age=30,
            song="Dior,Got it on me,welcome to the party",
            description = "Rapper",
            puppyImageId = R.drawable.popesmoke),
        Data(0,"Omah lay",
            sex="male",
            age=24,
            song="Godly,Damn,Bad Influence",
            description = "Afro  Beats Artist",
            puppyImageId = R.drawable.omaylay),

        Data(0,"Rihanna",
            sex="Female",
            age=44,
            song="Diamonds,Rude Boy,Umbrella",
            description = "great singer",
            puppyImageId = R.drawable.rihhna),
        Data(0,"Quavo",
            sex="male",
            age=39,
            song="Motor Sport,Bad and Boujee",
            description = "American Rapper",
            puppyImageId = R.drawable.quavo),
        Data(0,"Wizkid",
            sex="male",
            age=25,
            song="Joro,Essence,come Closer",
            description = "Afro Beats Artist",
            puppyImageId = R.drawable.wizkid),
        Data(0,"Card B",
            sex="Female",
            age=34,
            song="i Like it,Press,WAp",
            description = " American Rapper",
            puppyImageId = R.drawable.cardb),
    )
}